version: '3.7'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_dir:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5432:5432"
volumes:
  postgres_data_dir:
